server:
  port: 3004

spring:
  main:
    lazy-initialization: true
#    banner-mode: "off"
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop

logging:
  level:
    com.andruszkow: DEBUG
    #request logging
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    #spring framework
    org.springframework: WARN
    #everything else
    root: ERROR
